# Generated by Django 6.0.6 on 2026-06-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_location', models.CharField(db_index=True, max_length=255)),
                ('destination_location', models.CharField(db_index=True, max_length=255)),
                ('distance_miles', models.FloatField()),
                ('duration_minutes', models.FloatField()),
                ('geometry_json', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Route',
                'verbose_name_plural': 'Routes',
                'unique_together': {('start_location', 'destination_location')},
            },
        ),
    ]
